### ISSUE TITLE
Consider changing default set of records

### ISSUE THREAD

**Issue by svenstaro** [ogham/dog#8] opened 2020-11-09 14:55 UTC
I really like this tool! However, one convenience feature that I'm missing is "Just show me commonly useful information about this domain". I know that with `dig` and `drill` you can use `ANY` but that's not quite what I want in most cases. Frankly, I'd be happy about `ALL` or `--all` or something like that which showed the equivalent of `dog example.net A AAAA NS MX TXT SOA CNAME`. Personally, I'd even like that by default.

For instance, nowadays you at least have `A` and `AAAA` entries and `dog` by default only shows `A` which I don't think is very "modern" as a default. I know that other tools have the same default but in my understanding, `dog` is supposed to be convenient, too.

**Comment by beaugunderson** [comment] 2020-11-09 22:09
`ANY` already works with `dog` (or I've misunderstood how what you're asking for is different than `ANY`)

**Comment by svenstaro** [comment] 2020-11-10 05:21
Sorry, I was a bit tired when I wrote the feature request. What I want is a default preset that doesn't only get `A` (which appears to be the current default) but that gets a useful set of records for convenience (say `A`, `AAAA`, `NS`, `MX`, `TXT`, `SOA`, `CNAME`). I think the current default of getting `A` could be modernized/improved.

**Comment by beaugunderson** [comment] 2020-11-10 05:37
ah, I like that idea a lot—I usually want to see everything so it would
save me some typing :)

**Comment by apiraino** [comment] 2020-11-12 08:53
To my knowledge, the record type `ANY` is being deprecated [since quite some time](https://blog.cloudflare.com/deprecating-dns-any-meta-query-type/) and cannot be relied upon. In order to reproduce this behaviour probably a `--all` flag is more appropriate as issue reporter suggests.

**Comment by apiraino** [comment] 2020-11-12 09:37
> The default usage of `dog example.net` should already give you a useful common set of records to work with.

I stand corrected. `dog example.net` only shows the A record

**Comment by ogham** [comment] 2020-11-15 14:12
Hi,

This is a perfectly reasonable request to make, but I’m afraid that technical reasons make it difficult to implement, so I’ll be sticking with sending `A` as the default. Here’s my explanation:

1. Even though the DNS protocol allows for up to 2^16 (65536) records to be queried per request, all modern resolvers will [send back an error if you provide anything other than one](https://stackoverflow.com/a/4083071/3484614). There are good reasons for doing this (each response can only have one RCODE, so if looking up `A` is successful but looking up `AAAA` returns `QueryRefused` then there’s no way to signify this), and as of 2020, there’s no commonly-accepted alternative to just sending multiple packets. This is why, if you capture your own DNS traffic, you’ll see separate queries for `A` and `AAAA`.

    If dog were to send out seven queries by default, then we’d need to wait for seven responses to come back and handle retries seven times. We can’t even stream the results to the screen, because dog waits for all the responses so it knows how to format the table! I’ve used `dig` before to check how a DNS server is faring on a rocky, unstable network, and I don’t want dog’s _default_ behaviour in this situation to just sit there with no output until 100% of the packets return something.

2. DNS packets have three “sections” where records can go in a response: with a successful lookup, records will be in the “answer” section, but there can also be records in the “authoritative” and “additional” sections. For example, looking up a record type that doesn’t exist will return an empty “answer” section, but there’ll be a `SOA` record in the “additional” section.

    This means that, as dog is currently implemented, querying for more record types will result in multiples of this row being added to the table:

    ![Screenshot 2020-11-15 at 13 07 05](https://user-images.githubusercontent.com/503760/99187089-6d51b080-274c-11eb-81b8-7c5789e1fded.png)
    
    We could make it so only the “answer” section gets printed to the table by default with no arguments, but I think that would make things _more_ confusing in the general case. It also doesn’t help with records like `CNAME`, which also return the IP address of the domain they point to, if they happen to know it. The same thing happens with duplicates in the table:

    ![Screenshot 2020-11-15 at 13 26 29](https://user-images.githubusercontent.com/503760/99187099-7b073600-274c-11eb-9fc1-a3aca652e7f6.png)
    
    The more record types there are, the quicker the output turns into a mess.

3. Even if this functionality was behind an `--all` flag or something, there’s still the problem of which records belong in the list, and which do not. If you’re trying to get a complete overview of a domain, you probably want _at least_ the seven types you specify, plus relatively-common ones such as `CAA` or `SRV` or `SSHFP` or `TLSA` depending on what the domain is used for — and even these won’t return any records approximately 99.9% of the time.

    The `ANY` record, even if it weren’t soft-deprecated, is still limited to what the nameserver sends you back — if you want geniune responses for every record type, you’ll need to make them all individually. (Fun fact: the only reason I added support for the `HINFO` record type was that it gets used for `ANY` responses). And in this case, I don’t want to incur the wrath of any nameserver operators by making it easy to send lots of traffic to their networks after they’re explicitly disabled `ANY`.
    
In the future, I’d be open to having users be able to customise this (say, with an environment variable, or in a config file if dog ever has one) but I can’t realistically make anything other than `A` records the default. Thanks for understanding.

**Closed by ogham** 2020-11-15 14:12 UTC

**Comment by svenstaro** [comment] 2020-11-16 06:52
Thank you for your detailed explanation. I believe a compromise can still be found that strikes a balance between usability and correctness/responsiveness. See my comment in #31.

**Comment by polarathene** [comment] 2021-03-06 23:59
An `--all` flag seems like a good approach for this. I know I've wanted something like that when ANY isn't supported. I don't mind waiting for all responses if handling async display updates is problematic.

The suggestion of an ENV var to customize the queried records would work well for when `--all` defaults aren't desirable.

Regarding duplicates, if the result is being delayed/blocked until all responses are received, that should be something that could be filtered/sorted before outputting to stdout?
