### ISSUE TITLE
Error [network]

### ISSUE THREAD

**Issue by roman-lautenschlager** [ogham/dog#36] opened 2020-11-16 12:50 UTC
Can't get no response from dog.exe on Windows 10 machine.

Sometimes it just hangs and sometimes it says:
`Error [network]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)`

I've added Windows Firewall exception for dog.exe but it didn't help.

- The version of dog being used (`dog --version`)
v0.1.0

- The command-line arguments you are using
dog.exe example.net
.\dog.exe example.net MX

- Your operating system and hardware platform
Windows 10 Pro 20H2 (19042.630)

**Comment by Franky1** [comment] 2020-11-17 22:52
same for me with the windows binary on Win 10 Pro with the version `dog-v0.1.0-x86_64-pc-windows-msvc`

```shell
dog.exe google.de
Error [network]: invalid port value
```

**Comment by Franky1** [comment] 2020-11-17 22:54
Maybe duplicate of issue #12

**Closed** 2021-03-31 12:50 UTC
